LIBEVHTP_DIR = ../thirdparty/libevhtp
LIBEVHTP_OUTPUT = $(LIBEVHTP_DIR)/build
LIBEVHTP = $(LIBEVHTP_OUTPUT)/lib/libevhtp.a
LIBEVHTP_HEADERS = $(LIBEVHTP_OUTPUT)/include/evhtp.h
LIBEVHTP_HEADERS_ = evhtp.h
$(LIBEVHTP_HEADERS): $(LIBEVHTP)
$(LIBEVHTP_HEADERS_): $(LIBEVHTP)
$(LIBEVHTP):
	git submodule update --init $(LIBEVHTP_DIR)
	cd $(LIBEVHTP_OUTPUT) \
	&& cmake -DEVHTP_DISABLE_SSL=OFF -DEVHTP_BUILD_SHARED=ON -DEVHTP_DISABLE_REGEX=ON -DCMAKE_INSTALL_PREFIX=. ..  \
	&& make -j && make install

DEPS_STATIC_LIBS += $(LIBEVHTP)
INCFLAGS += -I$(LIBEVHTP_OUTPUT)/include -I$(LIBEVHTP_OUTPUT)/include/evhtp
